{
  "name": "Python 3",
  // Kullanılacak Docker imajı. Python 3.13 ile uyumlu hale getirildi.
  "image": "mcr.microsoft.com/devcontainers/python:1-3.13-bullseye",

  "customizations": {
    "codespaces": {
      "openFiles": [
        "README.md",
        "app.py"
      ]
    },
    "vscode": {
      "settings": {},
      "extensions": [
        "ms-python.python",
        "ms-python.vscode-pylance"
      ]
    }
  },

  // Konteyner başlatıldıktan sonra çalışacak komutlar.
  // 'requirements.txt' içindeki tüm Python paketlerini kurar.
  // 'streamlit' zaten requirements.txt içinde olduğu için ayrı bir kurulum komutuna gerek yoktur.
  "updateContentCommand": "[ -f packages.txt ] && sudo apt update && sudo apt upgrade -y && sudo xargs apt install -y <packages.txt; [ -f requirements.txt ] && pip3 install --user -r requirements.txt; echo '✅ Packages installed and Requirements met'",

  // Konteynere bağlandıktan sonra otomatik olarak çalıştırılacak komut.
  // Streamlit uygulamasını başlatır ve CORS/XSRF korumasını devre dışı bırakır (geliştirme ortamları için yaygın).
  "postAttachCommand": {
    "server": "streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false"
  },

  // Port yönlendirme ayarları.
  "portsAttributes": {
    "8501": {
      "label": "Application",
      "onAutoForward": "openPreview"
    }
  },
  "forwardPorts": [
    8501
  ]
}
